export enum EDUCATIONLEVEL {
	DIPLOMA = "DIPLOMA",
	ASSOCIATE = "ASSOCIATE",
	BACHELOR = "BACHELOR",
	MASTER = "MASTER",
	PROFESSIONAL = "PROFESSIONAL",
}

export enum APPOINTMENTSTATUS {
	IDLE = "IDLE",
	BOOKED = "BOOKED",
	PAID = "PAID",
	CANCEL = "CANCEL",
}
