import { User } from "./types";

export const mockUsers: Record<string, User> = {
	"admin@hospital.com": {
		id: "1",
		email: "admin@hospital.com",
		firstName: "John",
		lastName: "Administrator",
		role: "admin",
		department: "Administration",
		employeeId: "EMP001",
		permissions: [
			"user.create",
			"user.read",
			"user.update",
			"user.delete",
			"patient.create",
			"patient.read",
			"patient.update",
			"patient.delete",
			"staff.create",
			"staff.read",
			"staff.update",
			"staff.delete",
			"appointment.create",
			"appointment.read",
			"appointment.update",
			"appointment.delete",
			"analytics.read",
			"system.settings",
		],
	},
	"receptionist@hospital.com": {
		id: "2",
		email: "receptionist@hospital.com",
		firstName: "Sarah",
		lastName: "Johnson",
		role: "receptionist",
		department: "Front Desk",
		employeeId: "EMP002",
		permissions: [
			"patient.create",
			"patient.read",
			"patient.update",
			"appointment.create",
			"appointment.read",
			"appointment.update",
		],
	},
};
